RedisExchangeApi.Web/Models/ErrorViewModel.cs
namespace RedisExchangeApi.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

RedisExchangeApi.Web/Controllers/HashTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class HashTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase _db;
        private readonly string hashKey = "dictionary";

        public HashTypeController(RedisService redisService)
        {
            _redisService = redisService;
            _db = _redisService.GetDb(3);
        }

        public async Task<IActionResult> Index()
        {
            var dictionaryList = new Dictionary<string,string>();

            if(await _db.KeyExistsAsync(hashKey))
            {
                _db.HashGetAll(hashKey).ToList().ForEach(x=>{
                    dictionaryList.Add(x.Name.ToString(), x.Value.ToString());
                });
            }

            return View(dictionaryList);
        }

        [HttpPost]
        public async Task<IActionResult> Add(string name, string value)
        {
            await _db.HashSetAsync(hashKey, name, value);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string name)
        {
            await _db.HashDeleteAsync(hashKey, name);

            return RedirectToAction("Index");
        }
    }
}

RedisExchangeApi.Web/Controllers/ListTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class ListTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase _db;
        private readonly string listKey = "cars";

        public ListTypeController(RedisService redisService)
        {
            _redisService = redisService;
            _db = _redisService.GetDb(0);
        }

        public async Task<ActionResult> Index()
        {
            var cars = new List<string>();

            if (await _db.KeyExistsAsync(listKey))
            {
                var redisArray = await _db.ListRangeAsync(listKey);
                redisArray.ToList().ForEach(car=>{
                    cars.Add(car.ToString());
                });
            }

            return View(cars);
        }

        [HttpPost]
        public async Task<ActionResult> Add(string name)
        {
            await _db.ListRightPushAsync(listKey, name);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(string name)
        {
            await _db.ListRemoveAsync(listKey,name);
            return RedirectToAction("Index");
        }
    }
}

RedisExchangeApi.Web/Controllers/SetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class SetTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase _db;
        private readonly string listKey = "setnames";

        public SetTypeController(RedisService redisService)
        {
            _redisService = redisService;
            _db = _redisService.GetDb(1);
        }

        public async Task<IActionResult> Index()
        {
            var names = new HashSet<string>();

            if(await _db.KeyExistsAsync(listKey))
            {
                _db.SetMembers(listKey).ToList().ForEach(name=>{
                    names.Add(name.ToString());
                });
            }

            return View(names);
        }

        [HttpPost]
        public async Task<IActionResult> Add(string name)
        {
            await _db.KeyExpireAsync(listKey, DateTime.Now.AddSeconds(5));
            await _db.SetAddAsync(listKey, name);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string name)
        {
            await _db.SetRemoveAsync(listKey, name);

            return RedirectToAction("Index");

        }
    }
}

RedisExchangeApi.Web/Controllers/SortedSetTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class SortedSetTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase _db;
        private readonly string listKey = "sortedsetnames";

        public SortedSetTypeController(RedisService redisService)
        {
            _redisService = redisService;
            _db = _redisService.GetDb(2);
        }

        public async Task<IActionResult> Index()
        {
            var names = new HashSet<string>();

            if(await _db.KeyExistsAsync(listKey))
            {
                _db.SortedSetScan(listKey).ToList().ForEach(name=>{
                    names.Add(name.ToString());
                });
            }

            return View(names);
        }

        [HttpPost]
        public async Task<IActionResult> Add(string name, int score)
        {
            await _db.SortedSetAddAsync(listKey, name, score);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string name)
        {
            await _db.SortedSetRemoveAsync(listKey, name);

            return RedirectToAction("Index");
            
        }
    }
}

RedisExchangeApi.Web/Controllers/StringTypeController.cs
using Microsoft.AspNetCore.Mvc;
using RedisExchangeApi.Web.Services;
using StackExchange.Redis;

namespace RedisExchangeApi.Web.Controllers
{
    public class StringTypeController : Controller
    {
        private readonly RedisService _redisService;
        private readonly IDatabase _db;

        public StringTypeController(RedisService redisService)
        {
            _redisService = redisService;
            _db =_redisService.GetDb(0);
        }

        public async Task<IActionResult> Index()
        {
            //Creating string cache
            await _db.StringSetAsync("name", "memocan");
            await _db.StringSetAsync("visitor", 1);

            //Show string caches
            var name = await _db.StringGetAsync("name");
            var count = await _db.StringIncrementAsync("visitor", 1);

            ViewBag.name = name.HasValue ? name.ToString() : string.Empty;
            ViewBag.count = count > -1 ? count : 0;

            return View();
        }
    }
}

RedisExchangeApi.Web/Views/HashType/Index.cshtml
@model Dictionary<string,string>
@{
    ViewData["Title"] = "Hash Type Samples";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" placeholder="Name"/>
    <input type="text" name="value" placeholder="Value"/> 
    <button type="submit">Save</button>
</form>
<br>
@foreach (var item in Model){
    <h1>@item.Key => @item.Value <a asp-action="Delete" asp-route-name="@item.Key">delete</a></h1>
}

RedisExchangeApi.Web/Views/ListType/Index.cshtml
@model List<string>
@{
    ViewData["Title"] = "List Cache Samples";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" placeholder="Car Name"/>
    <button type="submit">Save</button>
</form>
<br>
@foreach (var item in Model){
    <h1>@item <a asp-controller="ListType" asp-action="Delete" asp-route-name="@item">delete</a></h1>
}

RedisExchangeApi.Web/Views/SetType/Index.cshtml
@model HashSet<string>
@{
    ViewData["Title"] = "Set Type Samples";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" placeholder="Name"/>
    <button type="submit">Save</button>
</form>
<br>
@foreach (var item in Model){
    <h1>@item <a asp-action="Delete" asp-route-name="@item">delete</a></h1>
}

RedisExchangeApi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedisExchangeApi.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RedisExchangeApi.Web.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RedisExchangeApi.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StringType"
                                asp-route-action="Index">String Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListType"
                                asp-route-action="Index">List Type </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SetType"
                                asp-route-action="Index">Set Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SortedSetType"
                                asp-route-action="Index">Sorted Set Type</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HashType"
                                asp-route-action="Index">Hash Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RedisExchangeApi.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

RedisExchangeApi.Web/Views/SortedSetType/Index.cshtml
@model HashSet<string>
@{
    ViewData["Title"] = "Sorte Set Type Samples";
}

<form method="post" asp-action="Add" enctype="application/x-www-form-urlencoded">
    <input type="text" name="name" placeholder="Name"/>
    <input type="number" name="score" placeholder="Score"/>
    <button type="submit">Save</button>
</form>
<br>
@foreach (var item in Model){
    <h1>@item <a asp-action="Delete" asp-route-name="@item">delete</a></h1>
}

RedisExchangeApi.Web/Views/StringType/Index.cshtml
@{
    ViewData["Title"] = "String Cache Samples";
}

<h1><label>User:</label> @ViewBag.name</h1>
<h1><label>Visit:</label> @ViewBag.count</h1>